#!/bin/sh
# Ensure that gzip -cdf handles mixed compressed/not-compressed data
# Before gzip-1.5, it would produce invalid output.

# Copyright (C) 2010 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# limit so don't run it by default.

if test "$VERBOSE" = yes; then
  set -x
  zgrep --version
fi

: ${srcdir=.}
. "$srcdir/tests/init.sh"

printf 'xxx\nyyy\n'      > exp2 || framework_failure
printf 'aaa\nbbb\nccc\n' > exp3 || framework_failure

fail=0

(echo xxx; echo yyy) > in || fail=1
gzip -cdf < in > out || fail=1
compare out exp2 || fail=1

# Uncompressed input, followed by compressed data.
# Currently fails, so skip it.
# (echo xxx; echo yyy|gzip) > in || fail=1
# gzip -cdf < in > out || fail=1
# compare out exp2 || fail=1

# Compressed input, followed by regular (not-compressed) data.
(echo xxx|gzip; echo yyy) > in || fail=1
gzip -cdf < in > out || fail=1
compare out exp2 || fail=1

(echo xxx|gzip; echo yyy|gzip) > in || fail=1
gzip -cdf < in > out || fail=1
compare out exp2 || fail=1

Exit $fail
