#!/bin/sh
# Check that znew -K works without compress(1).

# Copyright (C) 2010 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# limit so don't run it by default.

if test "$VERBOSE" = yes; then
  set -x
  gzip --version
fi

: ${srcdir=.}
. "$srcdir/tests/init.sh"; path_prepend_ "`pwd`"

cat <<'EOF' >compress || framework_failure
#!/bin/sh
echo >&2 'compress have been called'
exit 1
EOF
chmod +x compress || framework_failure

printf '%1012977s' ' ' | gzip -c >znew-k.Z || framework_failure

fail=0

znew -K znew-k.Z || fail=1
test -f znew-k.Z || fail=1

Exit $fail
